// <auto-generated />
namespace Saldo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V1040 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1040));
        
        string IMigrationMetadata.Id
        {
            get { return "202007312019248_V1.0.4.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
