//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PaginadoCantidadElementosPorPagina {
            get {
                return ((int)(this["PaginadoCantidadElementosPorPagina"]));
            }
            set {
                this["PaginadoCantidadElementosPorPagina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80mm Series Printer")]
        public string ImpresoraNombre {
            get {
                return ((string)(this["ImpresoraNombre"]));
            }
            set {
                this["ImpresoraNombre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nombre Comercio")]
        public string NombreFantasia {
            get {
                return ((string)(this["NombreFantasia"]));
            }
            set {
                this["NombreFantasia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dirección XXXX – Localidad")]
        public string Direccion {
            get {
                return ((string)(this["Direccion"]));
            }
            set {
                this["Direccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-----------------------------------")]
        public string ComprobanteCompraSeparador {
            get {
                return ((string)(this["ComprobanteCompraSeparador"]));
            }
            set {
                this["ComprobanteCompraSeparador"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comprobante de Compra\\r\\nNo valido como factura")]
        public string ComprobanteCompraCabecera {
            get {
                return ((string)(this["ComprobanteCompraCabecera"]));
            }
            set {
                this["ComprobanteCompraCabecera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gracias por su compra")]
        public string ComprobanteCompraPie {
            get {
                return ((string)(this["ComprobanteCompraPie"]));
            }
            set {
                this["ComprobanteCompraPie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AnticipacionAvisoIngresoMercaderia {
            get {
                return ((int)(this["AnticipacionAvisoIngresoMercaderia"]));
            }
            set {
                this["AnticipacionAvisoIngresoMercaderia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int VentaCategoriaNumeroFilas {
            get {
                return ((int)(this["VentaCategoriaNumeroFilas"]));
            }
            set {
                this["VentaCategoriaNumeroFilas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VentaCategoriaNumeroColumnas {
            get {
                return ((int)(this["VentaCategoriaNumeroColumnas"]));
            }
            set {
                this["VentaCategoriaNumeroColumnas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int VentaCategoriaProductosFilas {
            get {
                return ((int)(this["VentaCategoriaProductosFilas"]));
            }
            set {
                this["VentaCategoriaProductosFilas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int VentaCategoriaProductosColumnas {
            get {
                return ((int)(this["VentaCategoriaProductosColumnas"]));
            }
            set {
                this["VentaCategoriaProductosColumnas"] = value;
            }
        }
    }
}
