// <auto-generated />
namespace Producto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V1060 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1060));
        
        string IMigrationMetadata.Id
        {
            get { return "202008050025555_V1.0.6.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
